Add support for the java preview processor. Moved oae::preview_processor::init  to o::p::ruby

diff --git a/templates/run_preview_processor.sh.erb b/templates/run_preview_processor.sh.erb
--- a/templates/run_preview_processor.sh.erb
+++ b/templates/run_preview_processor.sh.erb
@@ -5,7 +5,12 @@
 # PASSWORD_FILE: path to file containing: system_url admin_password
 # PROCESSING_URL: url path to json containing items to be processed
 BASE_DIR="<%= scope.lookupvar('oae::params::basedir') %>"
+
+<% if scope.lookupvar('oae::preview_processor::common::pp_mode') == 'ruby' %>
 SCRIPT_DIR="${BASE_DIR}/nakamura/scripts";
+<% else if scope.lookupvar('oae::preview_processor::common::pp_mode') == 'java' %>
+SCRIPT_DIR="<%= scope.lookupvar('oae::preview_processor::java::working_directory') %>";
+<% end %>
 PASSWORD_FILE="${BASE_DIR}/.oae_credentials.txt";
 PROCESSING_URL="var/search/needsprocessing.json";
 ##############################################################################
@@ -69,17 +74,37 @@ touch ${SCRIPT_DIR}/.contentpreview.lock;
 check_processing_url=`curl --insecure --head --silent ${SAKAIOAE_URL}${PROCESSING_URL} | grep " 200 OK"`;
 
 if [ "${?}" = "0" ] ; then
-    # Run the preview processol:
-    ruby ${SCRIPT_DIR}/preview_processor.rb --server ${SAKAIOAE_URL} --password ${PASSWORD} --count 1 | grep -v "^I,";
-    # ruby scripts return 1 on success:
-    ruby_return_code=${?};
-    if [ "${ruby_return_code}" = "1" ] ; then
-        touch ${SCRIPT_DIR}/.contentpreview.success;
-    else
-        echo "ERROR: ruby ${SCRIPT_DIR}/preview_processor.rb returned non-one exit code: '${ruby_return_code}'";
-        rm -f ${SCRIPT_DIR}/.contentpreview.lock;
-        exit 7;
-    fi
+    # Run the preview processor:
+    <% if scope.lookupvar('oae::preview_processor::common::pp_mode') == 'ruby' %>
+        ruby ${SCRIPT_DIR}/preview_processor.rb --server ${SAKAIOAE_URL} --password ${PASSWORD} --count 1 | grep -v "^I,";
+
+        # ruby scripts return 1 on success:
+        return_code=${?};
+        if [ "${return_code}" = "1" ] ; then
+            touch ${SCRIPT_DIR}/.contentpreview.success;
+        else
+            echo "ERROR: ruby ${SCRIPT_DIR}/preview_processor.rb returned non-one exit code: '${return_code}'";
+            rm -f ${SCRIPT_DIR}/.contentpreview.lock;
+            exit 7;
+        fi
+
+    <% else if scope.lookupvar('oae::preview_processor::common::pp_mode') == 'java' %>
+        java -jar ${BASE_DIR}/preview/preview.jar --server ${SAKAIOAE_URL} \
+            --content <%= scope.lookupvar('oae::preview_processor::java::content_url') %> \
+            --user <%= scope.lookupvar('oae::preview_processor::common::user') %> \
+            --password <%= scope.lookupvar('oae::preview_processor::common::password') %> \
+            --directory <%= scope.lookupvar('oae::preview_processor::java::working_directory') %> \
+            --count 1 >> <%= scope.lookupvar('oae::params::preview_log_dir') %>/preview.log;
+        return_code=${?};
+        if [ "${return_code}" = "1" ] ; then
+            touch ${SCRIPT_DIR}/.contentpreview.success;
+        else
+            echo "ERROR: ruby ${SCRIPT_DIR}/preview_processor.rb returned non-one exit code: '${return_code}'";
+            rm -f ${SCRIPT_DIR}/.contentpreview.lock;
+            exit 7;
+        fi
+
+    <% end %>
 fi
 
 rm -f ${SCRIPT_DIR}/.contentpreview.lock;
